begin;

create extension if not exists pgcrypto;

create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  operation text not null check (operation in ('venta', 'alquiler')),
  property_type text not null,
  status text not null default 'draft' check (status in ('published', 'draft', 'paused')),
  featured boolean not null default false,
  price numeric,
  currency text not null default 'USD' check (currency in ('USD', 'ARS')),
  expenses numeric,
  address text,
  neighborhood text,
  city text default 'Capital Federal',
  province text not null default 'Ciudad Autónoma de Buenos Aires',
  description text,
  total_area numeric,
  covered_area numeric,
  rooms integer,
  bedrooms integer,
  bathrooms integer,
  garages integer,
  age integer,
  amenities jsonb not null default '[]'::jsonb,
  images jsonb not null default '[]'::jsonb,
  video_url text,
  external_url text,
  external_source text,
  seo_title text,
  seo_description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  email text not null,
  message text,
  type text not null default 'contact',
  property_id bigint references public.properties(id) on delete set null,
  read boolean not null default false,
  notification_status text not null default 'pending'
    check (notification_status in ('pending', 'sent', 'failed')),
  notification_error text,
  notified_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text not null,
  password text not null,
  name text,
  created_at timestamptz not null default now()
);

create unique index if not exists users_email_lower_idx
  on public.users (lower(email));
create index if not exists properties_public_listing_idx
  on public.properties (status, featured, created_at desc);
create index if not exists properties_location_idx
  on public.properties (city, neighborhood);
create index if not exists inquiries_created_at_idx
  on public.inquiries (created_at desc);
create index if not exists inquiries_property_id_idx
  on public.inquiries (property_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists properties_set_updated_at on public.properties;
create trigger properties_set_updated_at
before update on public.properties
for each row execute function public.set_updated_at();

alter table public.properties enable row level security;
alter table public.inquiries enable row level security;
alter table public.users enable row level security;

drop policy if exists "Public can read published properties" on public.properties;
create policy "Public can read published properties"
on public.properties
for select
to anon, authenticated
using (status = 'published');

revoke all on public.properties from anon, authenticated;
revoke all on public.inquiries from anon, authenticated;
revoke all on public.users from anon, authenticated;
grant select on public.properties to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'property-images',
  'property-images',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can read property images" on storage.objects;
create policy "Public can read property images"
on storage.objects
for select
to public
using (bucket_id = 'property-images');

commit;

